name: Project Packages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      #this doesn't do much for now, but for consistency....
      - name: Cleanup Residue
        run: |
          rm -rf .git .github

      #prepare PlatformIO project
      - name: Prepare PlatformIO project
        run: |
          bash -x ./scrips/setup-project.sh

      - name: Publish Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: iotc-arduino-platformio-sdk
          path: ./*

      - name: Prepare Arduino IDE project
        run: |
          bash -x ./scrips/setup-project.sh arduino-ide

      #use wildcards so that directory path is preserved.
      - name: Publish Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: iotc-arduino-ide-sdk
          path: esp-sensors-demo*/*
