name: Project Packages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      #this doesn't do much for now, but for consistency....
      - name: Setup Projects
        run: |
          bash -x ./scripts/setup-project.sh
      - name: Copy Supporting Docs and Licenses
        run: |
          cp  README.md LICENSE samples/
      #use wildcards so that directory path is preserved.
      - name: Publish Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: iotc-modustoolbox-sdk
          path: sample*/*